default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: financer_development

test:
  <<: *default
  database: financer_test
